[profile.default]
auto_detect_solc = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]
out = "out"
optimizer = true
optimizer_runs = 10_000_000

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = "single"